<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;

class EventTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (App::environment() != 'testing') {
            DB::statement('SET FOREIGN_KEY_CHECKS=0');

            DB::table('event_types')->truncate();
        }
        
        DB::table('event_types')->insert([
            [
                'name' => 'Error',
                'code' => 0,
                'description' => 'A special event reserved for if an error happens in the application. Assuming the application doesn\'t hard crash immediately, this gives us a way to debug and know if our application was having issues.',
            ],
            [
                'name' => 'Start Application',
                'code' => 1,
                'description' => 'When an application/kiosk is launched, it will send to our API some information which should be used to generate the AppID , which the API will then pass back to a Kiosk, so that the API knows how to associate additional information from the app.',
            ],
            [
                'name' => 'End Application',
                'code' => 2,
                'description' => 'Application itself has been closed (might not always be possible to capture this, depending how the app was closed)',
            ],
            [
                'name' => 'Scan',
                'code' => 3,
                'description' => 'Will either be a Badge ID OR a Temporary Local AttendeeID generated by the system and passed along to the Brandgage API to track this unknown attendee.',
            ],
            [
                'name' => 'Page',
                'code' => 4,
                'description' => '',
            ],
            [
                'name' => 'Popup',
                'code' => 5,
                'description' => '',
            ],
            [
                'name' => 'PDF',
                'code' => 6,
                'description' => '',
            ],
            [
                'name' => 'Video',
                'code' => 7,
                'description' => '',
            ],
            [
                'name' => 'Click',
                'code' => 8,
                'description' => '',
            ],
            [
                'name' => 'Swipe',
                'code' => 9,
                'description' => '',
            ],
            [
                'name' => 'Idle',
                'code' => 10,
                'description' => '',
            ],
            [
                'name' => 'Restart',
                'code' => 11,
                'description' => '',
            ],
            [
                'name' => 'Website',
                'code' => 12,
                'description' => '',
            ],
            [
                'name' => 'Custom',
                'code' => 13,
                'description' => '',
            ],
        ]);
        
        if (App::environment() != 'testing') {
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
        }
    }
}
